name: Release

on:
  push:
    tags:
      - "*"

permissions:
  contents: write
  metadata: read
  packages: read

jobs:
  ci:
    name: CI - Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: npm
      - run: npm install
      - run: npm t
      - name: Get current tag
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Generate release changelog
        run: npx news-fragments preview -p $RELEASE_VERSION >> release.txt
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body: cat release.txt
          # note you'll typically need to create a personal access token
          # with permissions to create releases in the other repo
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}